on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.18.1
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "release-bot@groww.in"
      - run: git config --global user.name "github-bot"
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
